images:
  urlService:
    tag: sha-fc76aed
  redirectService:
    tag: sha-01e0766
  analyticsService:
    tag: sha-01e0766
replicaCount:
  urlService: 2
  redirectService: 2
  analyticsService: 1
  postgres: 1
ingress:
  hosts:
    api: api.stg.galhalevi.dev
    redirect: r.stg.galhalevi.dev
    analytics: analytics.stg.galhalevi.dev
urlService:
  baseUrl: http://r.stg.galhalevi.dev
global:
  appEnv: stg
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
  prometheusRules:
    availability:
      enabled: true
    latencySLO:
      enabled: true
