images:
  urlService:
    tag: sha-fc76aed
  redirectService:
    tag: sha-01e0766
  analyticsService:
    tag: sha-01e0766
replicaCount:
  urlService: 3
  redirectService: 3
  analyticsService: 2
  postgres: 1
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: url-platform-prod-tls
      hosts:
        - api.galhalevi.dev
        - r.galhalevi.dev
        - analytics.galhalevi.dev
  hosts:
    api: api.galhalevi.dev
    redirect: r.galhalevi.dev
    analytics: analytics.galhalevi.dev
urlService:
  baseUrl: http://r.galhalevi.dev
global:
  appEnv: prod
