images:
  urlService:
    tag: sha-fc76aed
  redirectService:
    tag: sha-01e0766
  analyticsService:
    tag: sha-01e0766
replicaCount:
  urlService: 3
  redirectService: 3
  analyticsService: 2
  postgres: 1
ingress:
  # we will handle ssl in a following PR
  # annotations:
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    api: api.galhalevi.dev
    redirect: r.galhalevi.dev
    analytics: analytics.galhalevi.dev
urlService:
  baseUrl: http://r.galhalevi.dev
global:
  appEnv: prod
