images:
  urlService:
    tag: sha-5094a07
  redirectService:
    tag: sha-6b9af3a
  analyticsService:
    tag: sha-6b9af3a
ingress:
  hosts:
    api: api.dev.galhalevi.dev
    redirect: r.dev.galhalevi.dev
    analytics: analytics.dev.galhalevi.dev
urlService:
  baseUrl: http://r.dev.galhalevi.dev
global:
  appEnv: dev
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
  prometheusRules:
    availability:
      enabled: true
    latencySLO:
      enabled: true
