images:
  urlService:
    tag: sha-fc76aed
  redirectService:
    tag: sha-01e0766
  analyticsService:
    tag: sha-01e0766
ingress:
  hosts:
    api: api.dev.url-platform.local
    redirect: r.dev.url-platform.local
    analytics: analytics.dev.url-platform.local
urlService:
  baseUrl: http://r.dev.url-platform.local
global:
  appEnv: dev
