images:
  urlService:
    repository: ghcr.io/gal-halevi/url-service
    tag: sha-01e0766
    pullPolicy: IfNotPresent
  redirectService:
    repository: ghcr.io/gal-halevi/redirect-service
    tag: sha-01e0766
    pullPolicy: IfNotPresent
  analyticsService:
    repository: ghcr.io/gal-halevi/analytics-service
    tag: sha-01e0766
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent

replicaCount:
  urlService: 1
  redirectService: 1
  analyticsService: 1
  postgres: 1

ingress:
  enabled: true
  className: nginx
  nodePortHttp: 30000
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    enabled: true
    api: api.dev.url-platform.local
    redirect: r.dev.url-platform.local
    analytics: analytics.dev.url-platform.local
