images:
  urlService:
    tag: sha-b008313
  redirectService:
    tag: sha-01e0766
  analyticsService:
    tag: sha-01e0766
ingress:
  hosts:
    api: api.dev.galhalevi.dev
    redirect: r.dev.galhalevi.dev
    analytics: analytics.dev.galhalevi.dev
urlService:
  baseUrl: http://r.dev.galhalevi.dev
global:
  appEnv: dev
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
