images:
  urlService:
    tag: sha-9f17799
  redirectService:
    tag: sha-01e0766
  analyticsService:
    tag: sha-01e0766
ingress:
  hosts:
    api: api.dev.galhalevi.dev
    redirect: r.dev.galhalevi.dev
    analytics: analytics.dev.galhalevi.dev
urlService:
  baseUrl: http://r.dev.galhalevi.dev
global:
  appEnv: dev
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
  prometheusRules:
    availability:
      enabled: true
    latencySLO:
      enabled: true
      thresholdSeconds: "0.001"
      # make long windows short we don't wait 1h/6h
      fastShortWindow: 2m
      fastLongWindow: 10m
      slowShortWindow: 5m
      slowLongWindow: 15m

      # shorten the required "for" durations
      fastBurnFor: 30s
      slowBurnFor: 2m
