name: smoke-dev

on:
  push:
    branches: [main]
    paths:
      - "envs/dev/values.yaml"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: smoke-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  smoke:
    name: smoke-dev
    uses: ./.github/workflows/_smoke-env.yml
    with:
      env: dev
    secrets:
      URL_PLATFORM_INGRESS_ENDPOINT: ${{ secrets.URL_PLATFORM_INGRESS_ENDPOINT }}