name: smoke-stg

on:
  push:
    branches: [main]
    paths:
      - "envs/stg/values.yaml"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  smoke:
    uses: ./.github/workflows/_smoke-env.yml
    with:
      env: stg
    secrets:
      URL_PLATFORM_INGRESS_ENDPOINT: ${{ secrets.URL_PLATFORM_INGRESS_ENDPOINT }}